from typing import List, Dict, Optional


class IndianStandard:
    def __init__(self, id, title, category, subcategory, scope, keywords, description,
                 certification_required, qco_name=None, qco_effective_date=None,
                 certification_scheme='', product_examples=None, evidence_text='',
                 source='BIS', last_updated='', applicability_reason='',
                 what_it_covers=None, documents_needed=None):
        self.id = id
        self.title = title
        self.category = category
        self.subcategory = subcategory
        self.scope = scope
        self.keywords = keywords
        self.description = description
        self.certification_required = certification_required  # 'mandatory' | 'voluntary' | 'check_qco'
        self.qco_name = qco_name
        self.qco_effective_date = qco_effective_date
        self.certification_scheme = certification_scheme
        self.product_examples = product_examples or []
        self.evidence_text = evidence_text
        self.source = source
        self.last_updated = last_updated
        self.applicability_reason = applicability_reason
        self.what_it_covers = what_it_covers or []
        self.documents_needed = documents_needed or []

    def to_dict(self):
        return self.__dict__


INDIAN_STANDARDS: List[IndianStandard] = [
    IndianStandard(
        id='IS 302',
        title='Safety of Household and Similar Electrical Appliances',
        category='Electrical Appliances',
        subcategory='Household Appliances',
        scope='Safety requirements for household and similar electrical appliances including irons, fans, heaters, toasters, and other common kitchen and home appliances.',
        keywords=['electrical', 'appliance', 'safety', 'iron', 'fan', 'heater', 'toaster', 'kitchen', 'household', 'electric'],
        description='This standard specifies safety requirements for electrical appliances used in homes. It covers protection against electric shock, fire hazards, and mechanical dangers.',
        certification_required='mandatory',
        qco_name='Electrical Appliances Quality Control Order',
        qco_effective_date='2023-04-01',
        certification_scheme='ISI Mark',
        product_examples=['electric fan', 'electric iron', 'water heater', 'toaster', 'mixer grinder', 'electric kettle', 'room heater'],
        evidence_text='IS 302 is a comprehensive safety standard for household electrical appliances. Products covered under this standard require mandatory BIS certification as per the Electrical Appliances QCO.',
        source='Bureau of Indian Standards',
        last_updated='2024-01-15',
        applicability_reason='This standard applies to household electrical appliances including fans, irons, heaters, and kitchen appliances. It covers safety requirements that all such products must meet.',
        what_it_covers=['Electric shock protection', 'Fire and burn hazards', 'Mechanical safety', 'Abnormal operation', 'Radiation and laser safety', 'Chemical hazards'],
        documents_needed=['Product specifications', 'Electrical circuit diagrams', 'Test reports from BIS-recognized lab', 'Manufacturing process details', 'Quality control procedures'],
    ),
    IndianStandard(
        id='IS 1077',
        title='Common Portland Cement',
        category='Building Materials',
        subcategory='Cement',
        scope='Requirements for common Portland cement used in general construction purposes.',
        keywords=['cement', 'portland', 'construction', 'building', 'concrete', 'mortar', 'infrastructure'],
        description='Defines quality requirements for common Portland cement, the most widely used cement type in India for general construction.',
        certification_required='mandatory',
        qco_name='Portland Cement Quality Control Order',
        qco_effective_date='2023-03-01',
        certification_scheme='ISI Mark',
        product_examples=['Portland cement', 'OPC cement', 'cement bags', 'construction cement'],
        evidence_text='IS 1077 specifies requirements for common Portland cement. Mandatory BIS certification applies to all cement sold in India under the Portland Cement QCO.',
        source='Bureau of Indian Standards',
        last_updated='2024-01-10',
        applicability_reason='If you manufacture or sell Portland cement, this standard is mandatory under the applicable Quality Control Order.',
        what_it_covers=['Chemical composition', 'Physical requirements', 'Compressive strength', 'Setting time', 'Soundness', 'Fineness'],
        documents_needed=['Cement test reports', 'Manufacturing plant details', 'Raw material sources', 'Quality control records', 'Factory licence'],
    ),
    IndianStandard(
        id='IS 123',
        title='Steel Bars and Structural Steel',
        category='Building Materials',
        subcategory='Steel',
        scope='Requirements for mild steel and medium tensile steel bars and structural steel for construction.',
        keywords=['steel', 'bars', 'structural', 'construction', 'rebar', 'TMT', 'building', 'infrastructure'],
        description='Covers quality requirements for steel used in building construction, bridges, and infrastructure projects.',
        certification_required='mandatory',
        qco_name='Steel Products Quality Control Order',
        qco_effective_date='2023-06-01',
        certification_scheme='ISI Mark',
        product_examples=['steel bars', 'TMT bars', 'structural steel', 'mild steel plates', 'steel beams'],
        evidence_text='IS 123 covers requirements for steel products used in construction. Mandatory certification under Steel Products QCO.',
        source='Bureau of Indian Standards',
        last_updated='2024-02-01',
        applicability_reason='Steel products used in construction require BIS certification under the applicable QCO.',
        what_it_covers=['Tensile strength', 'Chemical composition', 'Dimensional tolerances', 'Surface quality', 'Marking requirements'],
        documents_needed=['Material test certificates', 'Manufacturing process details', 'Mill certificates', 'Quality control records'],
    ),
    IndianStandard(
        id='IS 252',
        title='Enamelled Ware',
        category='Household Items',
        subcategory='Kitchenware',
        scope='Requirements for enamelled iron and steel articles used for domestic purposes.',
        keywords=['enamel', 'cooking', 'utensils', 'kitchen', 'domestic', 'pots', 'pans'],
        description='Specifies requirements for enamelled cooking utensils and kitchenware for safe domestic use.',
        certification_required='check_qco',
        certification_scheme='ISI Mark',
        product_examples=['enamelled pots', 'enamelled pans', 'enamelled bowls', 'cooking vessels'],
        evidence_text='IS 252 covers quality requirements for enamelled kitchenware.',
        source='Bureau of Indian Standards',
        last_updated='2023-11-15',
        applicability_reason='Applies if you manufacture enamelled cooking utensils or kitchenware.',
        what_it_covers=['Material safety', 'Coating quality', 'Thermal resistance', 'Chemical resistance', 'Dimensional accuracy'],
        documents_needed=['Material composition reports', 'Test certificates', 'Manufacturing details'],
    ),
    IndianStandard(
        id='IS 695',
        title='LPG Domestic Gas Cooker',
        category='Gas Appliances',
        subcategory='Gas Stoves',
        scope='Requirements for LPG-fueled domestic gas cookers and stoves.',
        keywords=['gas', 'stove', 'LPG', 'cooker', 'kitchen', 'burner', 'flame', 'cooking'],
        description='Specifies safety and performance requirements for gas stoves and cookers running on LPG.',
        certification_required='mandatory',
        qco_name='LPG Domestic Gas Cooker Quality Control Order',
        qco_effective_date='2023-01-15',
        certification_scheme='ISI Mark',
        product_examples=['gas stove', 'LPG burner', 'gas cooker', 'kitchen gas stove', 'two-burner stove'],
        evidence_text='IS 695 is mandatory for LPG domestic gas cookers. The QCO requires BIS certification before sale.',
        source='Bureau of Indian Standards',
        last_updated='2024-03-01',
        applicability_reason='LPG gas cookers require mandatory BIS certification under the applicable QCO.',
        what_it_covers=['Gas tightness testing', 'Flame stability', 'Burner performance', 'Safety devices', 'Material quality', 'Marking and labelling'],
        documents_needed=['Product specifications', 'Gas flow test reports', 'Safety test certificates', 'Manufacturing process details', 'Quality manual'],
    ),
    IndianStandard(
        id='IS 15553',
        title='Packaged Drinking Water',
        category='Food & Beverages',
        subcategory='Water',
        scope='Requirements for packaged drinking water and mineral water.',
        keywords=['water', 'drinking', 'bottled', 'packaged', 'mineral', 'purified', 'BIS'],
        description='Covers quality and safety requirements for packaged drinking water sold in India.',
        certification_required='mandatory',
        qco_name='Packaged Drinking Water Quality Control Order',
        qco_effective_date='2022-04-01',
        certification_scheme='ISI Mark',
        product_examples=['packaged drinking water', 'mineral water', 'bottled water', 'water bottles'],
        evidence_text='IS 15553 is mandatory for all packaged drinking water sold in India.',
        source='Bureau of Indian Standards',
        last_updated='2024-01-20',
        applicability_reason='Packaged drinking water requires mandatory BIS certification.',
        what_it_covers=['Microbiological quality', 'Chemical parameters', 'Packaging requirements', 'Labelling', 'Production process', 'Testing frequency'],
        documents_needed=['Water quality test reports', 'Production facility details', 'Packaging specifications', 'Quality management system'],
    ),
    IndianStandard(
        id='IS 2885',
        title='Gold Hallmarking',
        category='Jewellery',
        subcategory='Gold',
        scope='Requirements for hallmarking of gold jewellery and artefacts.',
        keywords=['gold', 'hallmark', 'jewellery', 'HUID', 'purity', 'karat', '22k', '18k'],
        description='Specifies requirements for hallmarking gold jewellery to certify its purity.',
        certification_required='mandatory',
        qco_name='Gold Hallmarking Quality Control Order',
        qco_effective_date='2023-06-01',
        certification_scheme='BIS Hallmark',
        product_examples=['gold ring', 'gold necklace', 'gold bangles', 'gold earrings', 'gold chain'],
        evidence_text='IS 2885 covers hallmarking of gold jewellery. Mandatory hallmarking has been implemented in phases across India.',
        source='Bureau of Indian Standards',
        last_updated='2024-06-01',
        applicability_reason='Gold jewellery hallmarking is being made mandatory across India in phases.',
        what_it_covers=['Purity grades (14K, 18K, 22K, 24K)', 'HUID assignment', 'Hallmarking centre requirements', 'Assaying methods', 'Quality assurance'],
        documents_needed=['Jewellery specifications', 'Assaying reports', 'Hallmarking centre registration', 'Purity certificates'],
    ),
    IndianStandard(
        id='IS 4169',
        title='Aluminium Utensils',
        category='Household Items',
        subcategory='Kitchenware',
        scope='Requirements for aluminium cooking utensils.',
        keywords=['aluminium', 'utensils', 'cooking', 'kitchen', 'pots', 'pans', 'domestic'],
        description='Quality requirements for aluminium cooking vessels used in Indian households.',
        certification_required='voluntary',
        certification_scheme='ISI Mark',
        product_examples=['aluminium cooker', 'aluminium pressure cooker', 'aluminium pan', 'aluminium vessel', 'kadhai'],
        evidence_text='IS 4169 provides quality guidelines for aluminium cooking utensils.',
        source='Bureau of Indian Standards',
        last_updated='2023-09-01',
        applicability_reason='Applies to manufacturers of aluminium cooking utensils. Certification is voluntary but builds consumer trust.',
        what_it_covers=['Material composition', 'Food safety', 'Dimensional tolerances', 'Surface quality', 'Handle strength'],
        documents_needed=['Material composition analysis', 'Food contact safety reports', 'Manufacturing specifications'],
    ),
    IndianStandard(
        id='IS 2347',
        title='Safety Matches',
        category='Household Items',
        subcategory='Matches',
        scope='Requirements for safety matches for domestic use.',
        keywords=['matches', 'safety', 'fire', 'matchbox', 'household', 'combustion'],
        description='Specifications for safety matches ensuring they ignite only on the striking surface.',
        certification_required='mandatory',
        qco_name='Safety Matches Quality Control Order',
        qco_effective_date='2023-01-01',
        certification_scheme='ISI Mark',
        product_examples=['safety matches', 'matchboxes', 'match sticks'],
        evidence_text='IS 2347 covers safety matches. Mandatory BIS certification required.',
        source='Bureau of Indian Standards',
        last_updated='2023-12-01',
        applicability_reason='Safety match manufacturers must obtain BIS certification.',
        what_it_covers=['Ignition requirements', 'Flame characteristics', 'Chemical safety', 'Packaging', 'Storage stability'],
        documents_needed=['Chemical composition details', 'Ignition test reports', 'Manufacturing process', 'Storage test data'],
    ),
    IndianStandard(
        id='IS 374',
        title='Automobile Helmets',
        category='Automotive',
        subcategory='Safety Equipment',
        scope='Requirements for protective helmets for motorcycle riders.',
        keywords=['helmet', 'motorcycle', 'safety', 'protection', 'two-wheeler', 'riding'],
        description='Safety standards for motorcycle helmets to protect riders from head injuries.',
        certification_required='mandatory',
        qco_name='Protective Helmets for Two Wheeler Riders QCO',
        qco_effective_date='2023-01-01',
        certification_scheme='ISI Mark',
        product_examples=['motorcycle helmet', 'two-wheeler helmet', 'riding helmet', 'bike helmet'],
        evidence_text='IS 374 is mandatory for all motorcycle helmets sold in India.',
        source='Bureau of Indian Standards',
        last_updated='2024-02-15',
        applicability_reason='Motorcycle helmets require mandatory BIS certification.',
        what_it_covers=['Impact absorption', 'Penetration resistance', 'Chin strap strength', 'Peripheral vision', 'Shell integrity'],
        documents_needed=['Impact test reports', 'Shell material specifications', 'Retention system tests', 'Manufacturing quality plan'],
    ),
    IndianStandard(
        id='IS 15627',
        title='PVC Pipes for Water Supply',
        category='Building Materials',
        subcategory='Pipes',
        scope='Requirements for PVC pipes used in water supply and drainage.',
        keywords=['PVC', 'pipe', 'water', 'plumbing', 'drainage', 'construction', 'fitting'],
        description='Specifications for unplasticized PVC pipes used in water supply systems.',
        certification_required='check_qco',
        certification_scheme='ISI Mark',
        product_examples=['PVC pipe', 'water pipe', 'plumbing pipe', 'drainage pipe', 'uPVC pipe'],
        evidence_text='IS 15627 covers PVC pipe requirements. Check applicable QCO for mandatory status.',
        source='Bureau of Indian Standards',
        last_updated='2024-01-05',
        applicability_reason='PVC pipe manufacturers should verify certification requirements.',
        what_it_covers=['Pressure ratings', 'Dimensional accuracy', 'Material composition', 'Jointing methods', 'Marking requirements'],
        documents_needed=['Material test reports', 'Pressure test certificates', 'Dimensional inspection reports', 'Manufacturing process details'],
    ),
    IndianStandard(
        id='IS 732',
        title='Electrical Installation of Buildings',
        category='Electrical',
        subcategory='Wiring & Installation',
        scope='Requirements for electrical wiring and installation in buildings.',
        keywords=['electrical', 'wiring', 'installation', 'building', 'cable', 'conduit', 'switch', 'socket'],
        description='Comprehensive standard for electrical installations ensuring safety in buildings.',
        certification_required='voluntary',
        certification_scheme='Recommended Practice',
        product_examples=['electrical wiring', 'switch boards', 'distribution boards', 'cables for buildings'],
        evidence_text='IS 732 provides recommended practices for electrical installation in buildings.',
        source='Bureau of Indian Standards',
        last_updated='2023-10-01',
        applicability_reason='Electricians and building developers should follow this standard for safe installations.',
        what_it_covers=['Wiring methods', 'Earthing systems', 'Circuit protection', 'Load calculations', 'Inspection and testing'],
        documents_needed=['Building plans', 'Electrical drawings', 'Load assessment', 'Material specifications'],
    ),
    IndianStandard(
        id='IS 10322',
        title='Steel Drums and Barrels',
        category='Packaging',
        subcategory='Containers',
        scope='Requirements for steel drums and barrels for storage and transport.',
        keywords=['steel', 'drum', 'barrel', 'container', 'packaging', 'storage', 'transport'],
        description='Specifications for steel drums and barrels used in industrial packaging.',
        certification_required='voluntary',
        certification_scheme='ISI Mark',
        product_examples=['steel drums', 'steel barrels', 'industrial containers'],
        evidence_text='IS 10322 provides quality requirements for steel drums.',
        source='Bureau of Indian Standards',
        last_updated='2023-08-01',
        applicability_reason='Applies to manufacturers of steel drums and barrels.',
        what_it_covers=['Material specifications', 'Dimensional tolerances', 'Closure systems', 'Leak-proofness', 'Stacking strength'],
        documents_needed=['Material test reports', 'Dimensional inspection', 'Drop test reports', 'Leak-proofness test certificates'],
    ),
    IndianStandard(
        id='IS 6539',
        title='Steel Tubes for Structural Purposes',
        category='Building Materials',
        subcategory='Steel Tubes',
        scope='Requirements for steel tubes used in structural applications.',
        keywords=['steel', 'tube', 'structural', 'pipe', 'construction', 'framework'],
        description='Specifications for steel tubes used in building structures and frameworks.',
        certification_required='check_qco',
        certification_scheme='ISI Mark',
        product_examples=['structural steel tubes', 'steel pipes for construction', 'RHS tubes', 'CHS tubes'],
        evidence_text='IS 6539 covers structural steel tubes.',
        source='Bureau of Indian Standards',
        last_updated='2023-07-01',
        applicability_reason='Structural steel tube manufacturers should check applicable certification requirements.',
        what_it_covers=['Material composition', 'Mechanical properties', 'Dimensional tolerances', 'Surface finish', 'Weld quality'],
        documents_needed=['Mill test certificates', 'Dimensional reports', 'Weld inspection reports'],
    ),
    IndianStandard(
        id='IS 13939',
        title='LED Lamps',
        category='Electrical',
        subcategory='Lighting',
        scope='Requirements for LED lamps for general lighting purposes.',
        keywords=['LED', 'lamp', 'light', 'bulb', 'lighting', 'energy', 'illumination'],
        description='Quality and performance requirements for LED lamps used in homes and offices.',
        certification_required='mandatory',
        qco_name='LED Lamps Quality Control Order',
        qco_effective_date='2023-10-01',
        certification_scheme='CRS',
        product_examples=['LED bulb', 'LED tube light', 'LED panel light', 'LED lamp', 'LED downlight'],
        evidence_text='IS 13939 covers LED lamps. Mandatory BIS registration under CRS required.',
        source='Bureau of Indian Standards',
        last_updated='2024-04-01',
        applicability_reason='LED lamps require BIS registration under the Compulsory Registration Scheme.',
        what_it_covers=['Electrical safety', 'Luminous performance', 'Energy efficiency', 'Lifetime testing', 'Colour quality', 'EMC requirements'],
        documents_needed=['Test reports from NABL lab', 'Product specifications', 'Manufacturing details', 'Safety test certificates'],
    ),
    IndianStandard(
        id='IS 16046',
        title='Portable Electronic Products - Safety',
        category='Electronics',
        subcategory='Chargers & Adapters',
        scope='Safety requirements for portable electronic products including chargers and adapters.',
        keywords=['charger', 'adapter', 'mobile', 'phone', 'USB', 'electronic', 'power', 'safety'],
        description='Safety requirements for chargers, adapters, and portable electronic accessories.',
        certification_required='mandatory',
        qco_name='Electronics and IT Products QCO',
        qco_effective_date='2023-07-01',
        certification_scheme='CRS',
        product_examples=['mobile charger', 'USB adapter', 'power adapter', 'laptop charger', 'power bank'],
        evidence_text='IS 16046 covers safety of portable electronics. Registration under CRS mandatory.',
        source='Bureau of Indian Standards',
        last_updated='2024-03-15',
        applicability_reason='Electronic accessories like chargers require BIS CRS registration.',
        what_it_covers=['Electrical isolation', 'Overcurrent protection', 'Temperature testing', 'Material safety', 'EMC compliance'],
        documents_needed=['Safety test reports', 'EMC test reports', 'Product specifications', 'Circuit diagrams', 'Manufacturing details'],
    ),
    IndianStandard(
        id='IS 15490',
        title='Bottled Gas Stoves',
        category='Gas Appliances',
        subcategory='Portable Gas',
        scope='Requirements for bottled/camping gas stoves.',
        keywords=['camping', 'stove', 'portable', 'gas', 'bottled', 'outdoor'],
        description='Requirements for portable bottled gas stoves for camping and outdoor use.',
        certification_required='check_qco',
        certification_scheme='ISI Mark',
        product_examples=['camping stove', 'portable gas stove', 'bottle-top stove'],
        evidence_text='IS 15490 covers bottled gas stoves.',
        source='Bureau of Indian Standards',
        last_updated='2023-06-01',
        applicability_reason='Manufacturers of portable gas stoves should verify applicable requirements.',
        what_it_covers=['Gas connection safety', 'Flame performance', 'Stability', 'Material safety', 'Labelling'],
        documents_needed=['Gas flow test reports', 'Safety test certificates', 'Product specifications'],
    ),
    IndianStandard(
        id='IS 14846',
        title='Stainless Steel Utensils',
        category='Household Items',
        subcategory='Kitchenware',
        scope='Requirements for stainless steel cooking utensils and kitchenware.',
        keywords=['stainless steel', 'utensils', 'cooking', 'kitchen', 'pots', 'pans', 'steel'],
        description='Quality requirements for stainless steel kitchen utensils.',
        certification_required='voluntary',
        certification_scheme='ISI Mark',
        product_examples=['stainless steel water bottle', 'steel cooker', 'steel pan', 'steel plate', 'steel glass', 'steel tiffin'],
        evidence_text='IS 14846 provides quality requirements for stainless steel utensils.',
        source='Bureau of Indian Standards',
        last_updated='2024-01-01',
        applicability_reason='Applies to manufacturers of stainless steel kitchen utensils and water bottles.',
        what_it_covers=['Steel grade specification', 'Food safety', 'Dimensional accuracy', 'Surface quality', 'Corrosion resistance'],
        documents_needed=['Material composition analysis', 'Food safety test reports', 'Manufacturing specifications'],
    ),
    IndianStandard(
        id='IS 4736',
        title='Coconut Oil',
        category='Food & Beverages',
        subcategory='Edible Oils',
        scope='Requirements for coconut oil for edible purposes.',
        keywords=['coconut', 'oil', 'edible', 'food', 'cooking', 'virgin', 'refined'],
        description='Quality standards for coconut oil used in cooking and food preparation.',
        certification_required='check_qco',
        certification_scheme='ISI Mark',
        product_examples=['coconut oil', 'virgin coconut oil', 'refined coconut oil', 'cooking coconut oil'],
        evidence_text='IS 4736 specifies quality requirements for edible coconut oil.',
        source='Bureau of Indian Standards',
        last_updated='2023-05-01',
        applicability_reason='Edible oil manufacturers should check applicable labelling and quality requirements.',
        what_it_covers=['Quality parameters', 'Purity requirements', 'Peroxide value', 'Moisture content', 'Packaging and labelling'],
        documents_needed=['Quality test reports', 'Fatty acid composition', 'Purity certificates', 'Labelling compliance'],
    ),
    IndianStandard(
        id='IS 7720',
        title='Pressure Cookers',
        category='Kitchen Appliances',
        subcategory='Pressure Cookers',
        scope='Requirements for domestic pressure cookers.',
        keywords=['pressure cooker', 'cooker', 'kitchen', 'aluminium', 'steel', 'cooking', 'safety valve'],
        description='Safety and performance requirements for pressure cookers used in homes.',
        certification_required='mandatory',
        qco_name='Domestic Pressure Cooker Quality Control Order',
        qco_effective_date='2023-08-01',
        certification_scheme='ISI Mark',
        product_examples=['pressure cooker', 'cooker', 'stainless steel cooker', 'aluminium cooker', 'inner lid cooker'],
        evidence_text='IS 7720 covers domestic pressure cookers. Mandatory BIS certification required.',
        source='Bureau of Indian Standards',
        last_updated='2024-05-01',
        applicability_reason='Pressure cooker manufacturers must obtain BIS certification.',
        what_it_covers=['Pressure relief mechanisms', 'Body strength', 'Gasket performance', 'Handle safety', 'Cooking efficiency', 'Marking requirements'],
        documents_needed=['Safety valve test reports', 'Pressure testing certificates', 'Material specifications', 'Manufacturing quality plan', 'Gasket specifications'],
    ),
    IndianStandard(
        id='IS 13033',
        title='Emery and Corundum Abrasive',
        category='Industrial',
        subcategory='Abrasives',
        scope='Requirements for natural and manufactured abrasive materials.',
        keywords=['emery', 'corundum', 'abrasive', 'grinding', 'polishing', 'industrial'],
        description='Specifications for abrasive materials used in grinding and polishing.',
        certification_required='voluntary',
        certification_scheme='ISI Mark',
        product_examples=['emery powder', 'corundum wheels', 'abrasive grains'],
        evidence_text='IS 13033 covers abrasive material requirements.',
        source='Bureau of Indian Standards',
        last_updated='2023-04-01',
        applicability_reason='Applies to manufacturers of abrasive materials.',
        what_it_covers=['Grain size', 'Hardness', 'Chemical composition', 'Purity requirements'],
        documents_needed=['Sieve analysis', 'Hardness test reports', 'Chemical analysis'],
    ),
    IndianStandard(
        id='IS 12828',
        title='Three Phase Energy Meters',
        category='Electrical',
        subcategory='Meters',
        scope='Requirements for three-phase electricity meters.',
        keywords=['energy meter', 'electricity', 'meter', 'three phase', 'measuring', 'power'],
        description='Standards for three-phase energy meters used by utilities and industries.',
        certification_required='mandatory',
        qco_name='Energy Meters Quality Control Order',
        qco_effective_date='2023-05-01',
        certification_scheme='ISI Mark',
        product_examples=['three phase meter', 'energy meter', 'electricity meter', 'power meter'],
        evidence_text='IS 12828 covers three-phase energy meters. Mandatory certification required.',
        source='Bureau of Indian Standards',
        last_updated='2024-02-01',
        applicability_reason='Energy meter manufacturers must obtain BIS certification.',
        what_it_covers=['Accuracy requirements', 'Environmental testing', 'Insulation resistance', 'EMC compliance', 'Metering accuracy'],
        documents_needed=['Accuracy test reports', 'Environmental test certificates', 'EMC test reports', 'Manufacturing details'],
    ),
    IndianStandard(
        id='IS 1461',
        title='Electrical Moulded Case Circuit Breakers',
        category='Electrical',
        subcategory='Switchgear',
        scope='Requirements for moulded case circuit breakers up to 630A.',
        keywords=['circuit breaker', 'MCCB', 'electrical', 'switchgear', 'protection', 'distribution'],
        description='Standards for circuit breakers protecting electrical circuits.',
        certification_required='mandatory',
        qco_name='Electrical Switchgear QCO',
        qco_effective_date='2023-06-15',
        certification_scheme='ISI Mark',
        product_examples=['MCCB', 'circuit breaker', 'miniature circuit breaker', 'MCB', 'electrical protection'],
        evidence_text='IS 1461 covers moulded case circuit breakers. Mandatory certification required.',
        source='Bureau of Indian Standards',
        last_updated='2024-01-10',
        applicability_reason='Circuit breaker manufacturers need BIS certification.',
        what_it_covers=['Breaking capacity', 'Endurance testing', 'Temperature rise', 'Dielectric properties', 'Short circuit performance'],
        documents_needed=['Breaking capacity test reports', 'Endurance test certificates', 'Temperature rise data', 'Manufacturing specifications'],
    ),
    IndianStandard(
        id='IS 1155',
        title='Portland Pozzolana Cement',
        category='Building Materials',
        subcategory='Cement',
        scope='Requirements for Portland Pozzolana Cement (PPC).',
        keywords=['cement', 'PPC', 'pozzolana', 'construction', 'building', 'concrete'],
        description='Quality requirements for Portland Pozzolana Cement commonly used in construction.',
        certification_required='mandatory',
        qco_name='Portland Cement Quality Control Order',
        qco_effective_date='2023-03-01',
        certification_scheme='ISI Mark',
        product_examples=['PPC cement', 'Portland Pozzolana cement', 'pozzolana cement'],
        evidence_text='IS 1155 covers PPC. Mandatory BIS certification under Cement QCO.',
        source='Bureau of Indian Standards',
        last_updated='2024-01-10',
        applicability_reason='PPC manufacturers require mandatory BIS certification.',
        what_it_covers=['Chemical composition', 'Physical properties', 'Compressive strength', 'Fineness', 'Soundness'],
        documents_needed=['Test reports', 'Manufacturing details', 'Raw material analysis', 'Quality records'],
    ),
    IndianStandard(
        id='IS 4246',
        title='Domestic Electric Storage Water Heaters',
        category='Electrical Appliances',
        subcategory='Water Heaters',
        scope='Requirements for electric storage water heaters (geysers).',
        keywords=['water heater', 'geyser', 'electric', 'bathroom', 'hot water', 'storage'],
        description='Safety and performance requirements for electric water heaters.',
        certification_required='mandatory',
        qco_name='Electrical Appliances QCO',
        qco_effective_date='2023-04-01',
        certification_scheme='ISI Mark',
        product_examples=['water heater', 'geyser', 'electric geyser', 'storage water heater', 'instant geyser'],
        evidence_text='IS 4246 covers electric water heaters. Mandatory BIS certification required.',
        source='Bureau of Indian Standards',
        last_updated='2024-03-01',
        applicability_reason='Electric water heater manufacturers need BIS certification.',
        what_it_covers=['Electrical safety', 'Pressure testing', 'Thermal protection', 'Energy efficiency', 'Insulation', 'Heating element'],
        documents_needed=['Electrical safety test reports', 'Pressure vessel certificates', 'Thermostat calibration data', 'Manufacturing details'],
    ),
    IndianStandard(
        id='IS 4082',
        title='Wall Putty',
        category='Building Materials',
        subcategory='Paints & Coatings',
        scope='Requirements for wall putty for interior and exterior surfaces.',
        keywords=['wall putty', 'putty', 'paint', 'wall', 'building', 'interior', 'exterior'],
        description='Quality requirements for wall putty used before painting.',
        certification_required='voluntary',
        certification_scheme='ISI Mark',
        product_examples=['wall putty', 'white cement putty', 'interior putty', 'exterior putty'],
        evidence_text='IS 4082 provides quality requirements for wall putty.',
        source='Bureau of Indian Standards',
        last_updated='2023-09-01',
        applicability_reason='Wall putty manufacturers can benefit from voluntary BIS certification.',
        what_it_covers=['Adhesion strength', 'Coverage area', 'Drying time', 'Water resistance', 'Application properties'],
        documents_needed=['Adhesion test reports', 'Coverage analysis', 'Drying time tests', 'Water resistance data'],
    ),
    IndianStandard(
        id='IS 2048',
        title='Toys Safety',
        category='Toys & Children',
        subcategory='Toys',
        scope="Safety requirements for toys for children up to 14 years.",
        keywords=['toys', 'children', 'kids', 'safety', 'play', 'educational', 'game'],
        description="Comprehensive safety requirements for children's toys.",
        certification_required='mandatory',
        qco_name='Toys Quality Control Order',
        qco_effective_date='2023-04-01',
        certification_scheme='ISI Mark',
        product_examples=['toys', 'children toys', 'educational toys', 'soft toys', 'building blocks', 'toy car'],
        evidence_text='IS 2048 covers toy safety. Mandatory BIS certification required for all toys sold in India.',
        source='Bureau of Indian Standards',
        last_updated='2024-06-01',
        applicability_reason='All toy manufacturers must obtain BIS certification under the Toys QCO.',
        what_it_covers=['Sharp edges and points', 'Small parts safety', 'Flammability', 'Chemical limits', 'Age grading', 'Labelling'],
        documents_needed=['Safety test reports from BIS-recognized lab', 'Chemical analysis', 'Age grading documentation', 'Manufacturing process details'],
    ),
    IndianStandard(
        id='IS 9873',
        title='Cosmetics Safety',
        category='Personal Care',
        subcategory='Cosmetics',
        scope='Safety requirements for cosmetic products.',
        keywords=['cosmetic', 'beauty', 'cream', 'shampoo', 'makeup', 'personal care', 'skin'],
        description='Safety standards for cosmetic products sold in India.',
        certification_required='check_qco',
        certification_scheme='ISI Mark',
        product_examples=['face cream', 'shampoo', 'lipstick', 'foundation', 'moisturizer'],
        evidence_text='IS 9873 covers cosmetic safety requirements.',
        source='Bureau of Indian Standards',
        last_updated='2024-02-01',
        applicability_reason='Cosmetic manufacturers should check applicable safety requirements.',
        what_it_covers=['Microbiological safety', 'Heavy metal limits', 'Preservative limits', 'Packaging safety', 'Labelling'],
        documents_needed=['Microbiological test reports', 'Heavy metal analysis', 'Stability data', 'Ingredient lists'],
    ),
    IndianStandard(
        id='IS 14489',
        title='Domestic Non-Pressure Cooker',
        category='Kitchen Appliances',
        subcategory='Cookware',
        scope='Requirements for non-pressure cooking vessels.',
        keywords=['cooker', 'non-pressure', 'cooking', 'kitchen', 'vessel', 'pan', 'kadhai'],
        description='Standards for cooking vessels that operate without pressure.',
        certification_required='voluntary',
        certification_scheme='ISI Mark',
        product_examples=['kadhai', 'frying pan', 'sauce pan', 'tawa', 'cooking pot'],
        evidence_text='IS 14489 covers non-pressure cooking vessels.',
        source='Bureau of Indian Standards',
        last_updated='2023-10-01',
        applicability_reason='Cookware manufacturers can benefit from voluntary certification.',
        what_it_covers=['Material composition', 'Food safety', 'Handle durability', 'Heat distribution', 'Coating quality'],
        documents_needed=['Material certificates', 'Food safety test reports', 'Handle strength tests'],
    ),
    IndianStandard(
        id='IS 1658',
        title='Telephone Instruments',
        category='Electronics',
        subcategory='Telecom',
        scope='Requirements for telephone instruments and accessories.',
        keywords=['telephone', 'phone', 'landline', 'telecom', 'communication'],
        description='Standards for wired and wireless telephone instruments.',
        certification_required='mandatory',
        qco_name='Electronics and IT Products QCO',
        qco_effective_date='2023-07-01',
        certification_scheme='CRS',
        product_examples=['telephone', 'cordless phone', 'DECT phone'],
        evidence_text='IS 1658 covers telephone instruments. Registration under CRS required.',
        source='Bureau of Indian Standards',
        last_updated='2023-12-01',
        applicability_reason='Telephone manufacturers need BIS CRS registration.',
        what_it_covers=['Electrical safety', 'Acoustic performance', 'EMC requirements', 'Reliability testing'],
        documents_needed=['Safety test reports', 'EMC certificates', 'Acoustic test data'],
    ),
    IndianStandard(
        id='IS 15258',
        title='Domestic Liquid Butter',
        category='Food & Beverages',
        subcategory='Dairy',
        scope='Requirements for domestic liquid butter and similar products.',
        keywords=['butter', 'dairy', 'food', 'milk', 'ghee', 'cooking'],
        description='Quality standards for domestic butter and similar dairy products.',
        certification_required='check_qco',
        certification_scheme='ISI Mark',
        product_examples=['butter', 'liquid butter', 'table butter'],
        evidence_text='IS 15258 covers domestic liquid butter requirements.',
        source='Bureau of Indian Standards',
        last_updated='2023-07-01',
        applicability_reason='Dairy product manufacturers should check applicable food safety requirements.',
        what_it_covers=['Fat content', 'Moisture limits', 'Microbiological quality', 'Additive limits', 'Labelling'],
        documents_needed=['Quality test reports', 'Microbiological analysis', 'Composition analysis'],
    ),
    IndianStandard(
        id='IS 4682',
        title='Leather Goods',
        category='Textiles & Leather',
        subcategory='Leather',
        scope='Requirements for leather products and goods.',
        keywords=['leather', 'bags', 'wallet', 'shoes', 'belt', 'handbag', 'footwear'],
        description='Quality requirements for leather goods including bags, wallets, and accessories.',
        certification_required='voluntary',
        certification_scheme='ISI Mark',
        product_examples=['leather bag', 'leather wallet', 'leather belt', 'leather shoes'],
        evidence_text='IS 4682 provides quality requirements for leather goods.',
        source='Bureau of Indian Standards',
        last_updated='2023-08-01',
        applicability_reason='Leather goods manufacturers can benefit from voluntary BIS certification.',
        what_it_covers=['Material quality', 'Colour fastness', 'Tear strength', 'Chemical limits', 'Finish quality'],
        documents_needed=['Material test reports', 'Colour fastness tests', 'Chemical analysis'],
    ),
    IndianStandard(
        id='IS 14736',
        title='Hollow Concrete Blocks',
        category='Building Materials',
        subcategory='Blocks',
        scope='Requirements for hollow concrete blocks for masonry.',
        keywords=['concrete', 'block', 'hollow', 'brick', 'construction', 'masonry', 'building'],
        description='Quality standards for hollow concrete blocks used in construction.',
        certification_required='check_qco',
        certification_scheme='ISI Mark',
        product_examples=['hollow concrete block', 'concrete block', 'cement block', 'construction block'],
        evidence_text='IS 14736 covers hollow concrete blocks.',
        source='Bureau of Indian Standards',
        last_updated='2023-09-15',
        applicability_reason='Concrete block manufacturers should check applicable requirements.',
        what_it_covers=['Compressive strength', 'Water absorption', 'Dimensions', 'Surface quality', 'Marking'],
        documents_needed=['Compressive strength test reports', 'Dimensional inspection', 'Material composition'],
    ),
    IndianStandard(
        id='IS 3483',
        title='Steel Determination of Carbon',
        category='Metals',
        subcategory='Testing Methods',
        scope='Methods for determination of carbon content in steel.',
        keywords=['steel', 'carbon', 'testing', 'chemical analysis', 'metallurgy'],
        description='Standard methods for determining carbon content in steel and iron.',
        certification_required='voluntary',
        certification_scheme='Recommended Practice',
        product_examples=['steel testing', 'carbon analysis', 'steel quality check'],
        evidence_text='IS 3483 provides testing methods for carbon in steel.',
        source='Bureau of Indian Standards',
        last_updated='2023-03-01',
        applicability_reason='Steel manufacturers and testing labs use this standard for quality control.',
        what_it_covers=['Sample preparation', 'Combustion methods', 'Calculation', 'Precision requirements', 'Reporting'],
        documents_needed=['Test equipment calibration', 'Sample preparation details', 'Test procedure documentation'],
    ),
    IndianStandard(
        id='IS 4049',
        title='Ceramic Tiles',
        category='Building Materials',
        subcategory='Tiles',
        scope='Requirements for ceramic tiles for floor and wall use.',
        keywords=['ceramic', 'tiles', 'flooring', 'wall', 'building', 'construction', 'porcelain'],
        description='Quality requirements for ceramic tiles used in buildings.',
        certification_required='voluntary',
        certification_scheme='ISI Mark',
        product_examples=['ceramic tiles', 'floor tiles', 'wall tiles', 'porcelain tiles', 'vitrified tiles'],
        evidence_text='IS 4049 covers ceramic tile requirements.',
        source='Bureau of Indian Standards',
        last_updated='2023-11-01',
        applicability_reason='Tile manufacturers can benefit from voluntary BIS certification.',
        what_it_covers=['Breaking strength', 'Water absorption', 'Abrasion resistance', 'Chemical resistance', 'Dimensional accuracy'],
        documents_needed=['Test reports', 'Dimensional inspection', 'Material specifications'],
    ),
    IndianStandard(
        id='IS 15916',
        title='Basic Requirements for Safety of Power Converters',
        category='Electrical',
        subcategory='Power Electronics',
        scope='Safety requirements for power electronic converter systems.',
        keywords=['power', 'converter', 'inverter', 'UPS', 'power supply', 'electronic'],
        description='Safety requirements for power electronic equipment.',
        certification_required='mandatory',
        qco_name='Electronics and IT Products QCO',
        qco_effective_date='2023-07-01',
        certification_scheme='CRS',
        product_examples=['inverter', 'UPS', 'power supply', 'converter', 'adapter'],
        evidence_text='IS 15916 covers power converter safety. CRS registration required.',
        source='Bureau of Indian Standards',
        last_updated='2024-02-01',
        applicability_reason='Power electronics manufacturers need BIS CRS registration.',
        what_it_covers=['Electrical safety', 'Overcurrent protection', 'Temperature limits', 'EMC requirements', 'Marking'],
        documents_needed=['Safety test reports', 'EMC certificates', 'Technical specifications'],
    ),
    IndianStandard(
        id='IS 8125',
        title='Footwear Safety',
        category='Textiles & Leather',
        subcategory='Footwear',
        scope='Safety requirements for footwear products.',
        keywords=['shoes', 'footwear', 'safety', 'boots', 'sandals', 'leather'],
        description='Quality and safety standards for footwear products.',
        certification_required='check_qco',
        certification_scheme='ISI Mark',
        product_examples=['safety shoes', 'leather shoes', 'sandals', 'boots', 'footwear'],
        evidence_text='IS 8125 covers footwear safety requirements.',
        source='Bureau of Indian Standards',
        last_updated='2024-01-15',
        applicability_reason='Footwear manufacturers should check applicable requirements.',
        what_it_covers=['Sole strength', 'Upper material', 'Slip resistance', 'Chemical safety', 'Durability'],
        documents_needed=['Material test reports', 'Sole strength tests', 'Chemical analysis'],
    ),
    IndianStandard(
        id='IS 13360',
        title='Steel Pipes for Water and Sewage',
        category='Building Materials',
        subcategory='Pipes',
        scope='Requirements for steel pipes used in water supply and sewage systems.',
        keywords=['steel', 'pipe', 'water', 'sewage', 'plumbing', 'drainage'],
        description='Specifications for steel pipes in water and sewage infrastructure.',
        certification_required='check_qco',
        certification_scheme='ISI Mark',
        product_examples=['steel pipe', 'water pipe', 'sewage pipe', 'GI pipe', 'galvanized pipe'],
        evidence_text='IS 13360 covers steel pipes for water and sewage.',
        source='Bureau of Indian Standards',
        last_updated='2023-08-15',
        applicability_reason='Steel pipe manufacturers should check applicable certification.',
        what_it_covers=['Material grade', 'Corrosion protection', 'Joint tightness', 'Pressure ratings', 'Dimensional accuracy'],
        documents_needed=['Material certificates', 'Pressure test reports', 'Corrosion test data'],
    ),
    IndianStandard(
        id='IS 14828',
        title='Aluminium Conductors',
        category='Electrical',
        subcategory='Cables',
        scope='Requirements for aluminium conductors for overhead power transmission.',
        keywords=['aluminium', 'conductor', 'power', 'transmission', 'overhead', 'cable', 'wire'],
        description='Standards for aluminium conductors used in power transmission lines.',
        certification_required='mandatory',
        qco_name='Electrical Cables QCO',
        qco_effective_date='2023-05-01',
        certification_scheme='ISI Mark',
        product_examples=['aluminium conductor', 'ACSR conductor', 'overhead line conductor'],
        evidence_text='IS 14828 covers aluminium conductors. Mandatory certification required.',
        source='Bureau of Indian Standards',
        last_updated='2024-01-20',
        applicability_reason='Conductor manufacturers need BIS certification.',
        what_it_covers=['Conductivity', 'Tensile strength', 'Strand construction', 'Dimensions', 'Corrosion resistance'],
        documents_needed=['Conductivity test reports', 'Tensile test certificates', 'Dimensional reports'],
    ),
    IndianStandard(
        id='IS 1678',
        title='Electronic Weighing Instruments',
        category='Measuring Instruments',
        subcategory='Weighing',
        scope='Requirements for electronic weighing instruments.',
        keywords=['weighing', 'scale', 'balance', 'electronic', 'measurement', 'digital'],
        description='Standards for electronic weighing instruments for commercial and industrial use.',
        certification_required='mandatory',
        qco_name='Legal Metrology QCO',
        qco_effective_date='2023-03-01',
        certification_scheme='ISI Mark',
        product_examples=['electronic scale', 'digital weighing machine', 'bench scale', 'platform scale'],
        evidence_text='IS 1678 covers electronic weighing instruments.',
        source='Bureau of Indian Standards',
        last_updated='2023-12-15',
        applicability_reason='Weighing instrument manufacturers need verification and certification.',
        what_it_covers=['Accuracy class', 'Repeatability', 'Temperature effects', 'EMC requirements', 'Load cell specifications'],
        documents_needed=['Calibration certificates', 'Accuracy test reports', 'EMC test data', 'Technical specifications'],
    ),
    IndianStandard(
        id='IS 11654',
        title='Safety Glass',
        category='Building Materials',
        subcategory='Glass',
        scope='Requirements for safety glass for buildings and vehicles.',
        keywords=['glass', 'safety', 'tempered', 'laminated', 'building', 'automobile'],
        description='Standards for safety glass to prevent injury from breakage.',
        certification_required='check_qco',
        certification_scheme='ISI Mark',
        product_examples=['tempered glass', 'laminated glass', 'safety glass', 'automobile glass'],
        evidence_text='IS 11654 covers safety glass requirements.',
        source='Bureau of Indian Standards',
        last_updated='2023-10-15',
        applicability_reason='Glass manufacturers should check applicable safety requirements.',
        what_it_covers=['Impact resistance', 'Fragmentation', 'Transparency', 'Thickness', 'Edge finish'],
        documents_needed=['Impact test reports', 'Fragmentation test data', 'Material specifications'],
    ),
]


# Whitelist of verified IS codes
VERIFIED_IS_CODES: List[str] = list({s.id for s in INDIAN_STANDARDS})
IS_CODE_WHITELIST: set = set(VERIFIED_IS_CODES)
